#  ______   __            _____  ____
# /\__  _\ /\ \__        /\___ \/\  _`\
# \/_/\ \/ \ \ ,_\   ____\/__/\ \ \ \L\ \     __   __  __
#    \ \ \  \ \ \/  /',__\  _\ \ \ \  _ <'  /'__`\/\ \/\ \
#     \_\ \__\ \ \_/\__, `\/\ \_\ \ \ \L\ \/\  __/\ \ \_\ \
#     /\_____\\ \__\/\____/\ \____/\ \____/\ \____\\/`____ \
#     \/_____/ \/__/\/___/  \/___/  \/___/  \/____/ `/___/> \
#                                                      /\___/
#                                                      \/__/   presents LookTeleporter

# Set the Teleport Cooldown time here. The format will be in seconds. The defualt will be 60
Cooldown: 60

# Set the Teleport Delay. This defines how long it takes to not move till the teleport commences.
Teleport-Delay: 3

# In this variable you can set the distance a player should be able to teleport.
Max-Distance: 50

# Here you can set the permission that is needed to teleport around. - leave empty for none
Permission: "lookteleport.use"

# Here you can set the permission to bypass the cooldown - leave empty for none
Bypass-Permission: "lookteleport.bypass"